
-- ZENTRIQ LOGISTICS - SUPABASE SCHEMA INITIALIZATION
-- RUN THIS IN THE SUPABASE SQL EDITOR

-- 1. Create Shipments Table
CREATE TABLE IF NOT EXISTS shipments (
    id TEXT PRIMARY KEY,
    "trackingNumber" TEXT UNIQUE NOT NULL,
    "senderName" TEXT NOT NULL,
    "senderPhone" TEXT,
    "receiverName" TEXT NOT NULL,
    "receiverPhone" TEXT,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    "currentLocation" TEXT,
    weight TEXT,
    dimensions TEXT,
    "serviceType" TEXT,
    status TEXT DEFAULT 'Pending',
    progress INTEGER DEFAULT 0,
    "estimatedDelivery" TEXT,
    "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Shipment Updates Table (Relational History)
CREATE TABLE IF NOT EXISTS shipment_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES shipments(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    location TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL
);

-- 3. Security: Enable RLS
ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_updates ENABLE ROW LEVEL SECURITY;

-- 4. Security: Public Read Access (Tracking)
CREATE POLICY "Public Read Access Shipments" ON shipments FOR SELECT USING (true);
CREATE POLICY "Public Read Access Updates" ON shipment_updates FOR SELECT USING (true);

-- 5. Security: Admin Full Access (Development Policy)
-- Note: Replace true with auth.uid() checks for production auth
CREATE POLICY "Admin Full Access Shipments" ON shipments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access Updates" ON shipment_updates FOR ALL USING (true) WITH CHECK (true);

-- 6. Verify Relationships
-- Ensure foreign key linking is active for nested selection in JS:
-- .select('*, updates:shipment_updates(*)')
